### ISSUE TITLE
Qurro will break on newer (>= 2020.11) versions of QIIME 2

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#315]
Due to #258 -- ideally we will need to cut a new release that uses pandas 1, and clearly document which version to install based on the version of QIIME 2 in use.

For now, a faster solution would be just clearly documenting somewhere that Qurro, for now, can't work with QIIME 2 2020.11 and future versions, due to the pandas thing.

**Comment by astrophys** [comment]
A specific source of difficulties : 
1. Qiime2/2021.8, using conda installs  pandas-1.2.5 + numpy-1.21.2. 
2. When I installed qurro (using pip), it depends on pandas < 1.0 and > 0.24, so pip happily _uninstalled_ pandas-1.2.5 and downgraded it to pandas-0.25.3.
3.  pandas-0.25.3 is NOT compatible with numpy-1.21.2,  e.g. 
```
>>> import pandas as pd
>>> df =  pd.DataFrame(columns=['SubjectID1', 'SubjectID2', 'Group1','Group2', 'Distance'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/apps/opt/QIIME2/2021.8/envs/qiime2/lib/python3.8/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/export/apps/opt/QIIME2/2021.8/envs/qiime2/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/export/apps/opt/QIIME2/2021.8/envs/qiime2/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1221, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```
4. So to 'fix' this, I used pip to install numpy-1.19.5,  e.g. `pip install --prefix /path/to/QIIME2/2021.8/envs/qiime2/ numpy==1.19.5`

It 'fixes' that error, but it is unclear how this may break other feautures / functionality of qiime2.

**Comment by ElDeveloper** [comment]
Any updates on this ticket? Just ran into this problem running the latest version of QIIME2. Also noticed the altair version is pinned at exactly `3.1.0` which is almost 3 years old, it would be nice if the version requirements were a little more forgiving.

**Comment by fedarko** [comment]
Sorry, I don't have an update on this yet. The pandas (and altair) updates
are both definitely surmountable, but these changes -- mostly the altair
one -- will involve changing an uncomfortably large amount of the codebase.

The pandas issue is probably easier to fix since it only impacts the Python
side of things. However, the altair pin is (IIRC) due to mismatches with
the Vega-Lite version used by newer versions of altair (
https://github.com/biocore/qurro/issues/216), so even if we update it on
the Python side we'll need to make sure that everything on the JS side
works properly. This is doable! However, I'm very hesitant to risk breaking
things, especially since I haven't touched this codebase in a while.

For now, the shoddy workaround solution is installing an older version of
QIIME 2 (2020.8 should be the latest version that works, due to the pandas
version used) and then installing Qurro into that QIIME 2 environment.
However, I recognize this is not ideal, and if time permits I'd like to fix
this situation. Sorry for the trouble; PRs are welcome in case anyone wants
to take a crack at this.

**Comment by ElDeveloper** [comment]
Thanks for the update! 😵

**Comment by fedarko** [comment]
I apologize for the long delay in fixing this. Qurro v0.8.0 is now available [on PyPI](https://pypi.org/project/qurro/) (the conda-forge version should be automatically updated soon), and supports all versions of QIIME 2 ≥ 2020.11.
